services:
  app:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/pls
      LOGIN_API_KEY: super_secret
      LOGIN_API_URL: http://login:7002
      LOGIN_FRONTEND_URL: http://localhost:7002
      PORT: 4000
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    command: "bash -c '/app/bin/migrate && /app/bin/server'"
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pls
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 2s
      timeout: 2s
      retries: 3
  login:
    image: ghcr.io/datasektionen/nyckeln-under-dorrmattan
    ports:
      - 7002:7002
