FROM elixir:1.17.2

# Dependencies
RUN apt update \
    && apt upgrade -y \
    && apt install -y bash curl git build-essential inotify-tools

# Phoenix
RUN mix local.hex --force
RUN mix local.rebar --force

# App Directory
ENV APP_HOME=/app
RUN mkdir -p $APP_HOME
WORKDIR $APP_HOME

# App Port
EXPOSE 4000

# Default Command
CMD ["mix", "run", "--no-halt"]
